package it.uniud.easyhome.network;

public enum NetworkJobType {

	NODE_DESCR_REQUEST,
	NODE_NEIGH_REQUEST,
	NODE_ACTIVE_ENDPOINTS_REQUEST,
	SIMPLE_DESCRIPTOR_REQUEST,
	NODE_LIVENESS_POLL,
	NODE_FAILURE_DETECTION,
	NODE_POWER_LEVEL_REQUEST,
	NODE_POWER_LEVEL_SET
}
